
function imex()
    handles=struct;
    handles=window_initialize(handles);
end


function handles=window_initialize(handles)
    
    xleft_ax1=20;
    ybot_ax1=20;
    w_ax1=650;h_ax1=w_ax1;
    w_ax2=250;h_ax2=w_ax2;
    w_but=80;h_but=25;
    xdist_axbut=30;
    xinit_but=xleft_ax1+w_ax1+xdist_axbut;
    yinit_but=670-h_but;
    xdist_but=20+w_but;ydist_but=10+h_but;
    
    handles.figure1=figure( ...
        'Units','pixels', ...
        'Position',[10,50,1250,720]);
    fig1=handles.figure1;

    handles.axes1=axes(fig1, ...
        'Units','pixels', ...
        'Position',[20,ybot_ax1,w_ax1,h_ax1], ...
        'XTick',[], ...
        'YTick',[], ...
        'XColor','w', ...
        'YColor','w');
    ax1=handles.axes1;
    handles.axes2=axes(fig1, ...
        'Units','pixels', ...
        'Position',[xinit_but,ybot_ax1,w_ax2,h_ax2], ...
        'XTick',[], ...
        'YTick',[], ...
        'XColor','w', ...
        'YColor','w');
    ax2=handles.axes2; 
    
    handles.edit1=uicontrol(fig1, ...
        'Style','edit', ...
        'Position',[20,680,60,20]);

    % % first coloumn
    handles.ButNext=uicontrol(fig1, ...
        'Style','pushbutton', ...
        'Position',[xinit_but,yinit_but,w_but,h_but],...
        'String','>>');
    handles.ButPrevious=uicontrol(fig1, ...
        'Style','pushbutton', ...
        'Position',[xinit_but,yinit_but-ydist_but,w_but,h_but],...
        'String','<<');
    handles.ButResize=uicontrol(fig1, ...
        'Style','pushbutton', ...
        'Position',[xinit_but,yinit_but-2*ydist_but,w_but,h_but],...
        'String','resize'); 
    handles.ButBoxSelect=uicontrol(fig1, ...
        'Style','togglebutton', ...
        'Position',[xinit_but,yinit_but-3*ydist_but,w_but,h_but],...
        'String','box select'); 
    handles.ButResize=uicontrol(fig1, ...
        'Style','pushbutton', ...
        'Position',[xinit_but,yinit_but-4*ydist_but,w_but,h_but],...
        'String','segment');
    handles.ButSeperateObject=uicontrol(fig1, ...
        'Style','pushbutton', ...
        'Position',[xinit_but,yinit_but-5*ydist_but,w_but,h_but],...
        'String','seperate object');    
    handles.ButDetectAxis=uicontrol(fig1, ...
        'Style','pushbutton', ...
        'Position',[xinit_but,yinit_but-6*ydist_but,w_but,h_but],...
        'String','detect axis');    
    % % second coloumn
    handles.ButLoadProject=uicontrol(fig1, ...
        'Style','pushbutton', ...
        'Position',[xinit_but+xdist_but,yinit_but,w_but,h_but],...
        'String','load project');
    handles.ButSaveProject=uicontrol(fig1, ...
        'Style','pushbutton', ...
        'Position',[xinit_but+xdist_but,yinit_but-ydist_but,w_but,h_but],...
        'String','save project');
    handles.ButResize=uicontrol(fig1, ...
        'Style','pushbutton', ...
        'Position',[xinit_but+xdist_but,yinit_but-2*ydist_but,w_but,h_but],...
        'String','import image');     
    handles.ButResize=uicontrol(fig1, ...
        'Style','pushbutton', ...
        'Position',[xinit_but+xdist_but,yinit_but-3*ydist_but,w_but,h_but],...
        'String','delete box'); 
    w_tabgr=250;h_tabgr=300;
    xinit_tabgr=980;yinit_tabgr=ybot_ax1+h_ax1-h_tabgr;
    % % tab panel
%     handles.Tabgp=uitabgroup(fig1, ...
%         'Units','pixels', ...
%         'Position',[xinit_tabgr,yinit_tabgr,w_tabgr,h_tabgr])
%     tabgp1=handles.Tabgp;
%     handles.TabFile=uitab(tabgp1,...
%         'Title','File');
%     handles.TabSetting=uitab(tabgp1,...
%         'Title','Setting');    
%     tab1=handles.TabFile;
    % %
    handles.TableFile=uitable(fig1, ...
        'Units','pixels', ...
        'Position',[xinit_tabgr,yinit_tabgr,w_tabgr,h_tabgr], ...
        'Data',{'01.jpeg';'02.png'});

end
